### ISSUE TITLE
新功能：死亡惩罚

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#20]
前提：#19

用于代替目前的死亡惩罚插件。

配置文件内容

```
death_penalty:
  worlds: # following worlds enables penalty
  - world
  - world_nether
  - someotherworlds
  penalty:
    min: 100  # minimum penalty
    max: 1000  # maximum penalty
    percent: 10  # based on player's balance
```

即在定义的世界中死亡，玩家会被扣除自身 player balance 的 10% 金钱。如 player balance 过低或过高，则最低扣除 100 最高扣除 1000。如果玩家 player balance 为负，首先取绝对值再计算要扣除的金钱数。如果玩家 player balance 为 0，扣除最低的数量，即 100。

从玩家死亡扣除的金钱，保存到 `balance` 中。
