### ISSUE TITLE
新功能：广告

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#24]
因为牌子商店有时不便查找，因此结合广告功能可以提升销售量。

配置文件 `config.yml` 部分

```
ads:
  interval: 600 # 每 600 tick 展示一条广告
  count-afk: false # 不计算 afk 玩家的展示量
  count-self: false # 不计算广告主玩家的展示量
  price: 10 # 价格 per 展示量
  max_display: 200 # 最大允许的展示量
  color: true # 允许使用颜色代码( `0 ~ f` )
  formatting: # 允许使用的样式代码
  - l
  - m
  - n
  - o
  - r
  limit_group:
    default: 2 # 默认玩家组可以发布 2 条广告
    advance: 3 # advance 组玩家可以发布 3 条
  limit_total: 100  # 总计有效的广告数量限制
  limit_text: 140 # 每条广告允许的字符长度
```

配置文件 `ads.yml`

```
ads:
  '0':  # 广告 ID
    text: '&asome &rads text here' # 广告文本
    player: [UUID]  # 广告主玩家 UUID
    display_total: 100  # 总计展示量
    displayed: 10  # 已经消耗的展示量
mute:
- player1 uuid
- player2 uuid
```

命令：

* `/heh ads list` - 查看当前发布的广告，样例文本：

```
Your active ads:
- [AD ID] 'ad text' (displayed/total)
- [5] 'my ad text lol' (30/100) # AD ID 是配置文件中的 ID
```

* `/heh ads add [text] [display amount]` 添加广告文本并指定展示次数，并支付 `display amount * price` 的费用到系统 balance。如果文本中带有空格，使用反引号将整个文本括起来

* `/heh ads revoke [ID]` - 撤回对应 ID 的广告。玩家只能撤回 ID 属于自己的广告，不能撤回他人的广告。撤回广告不会退回广告费用。

* `/heh ads [mute|unmute]` - 屏蔽广告，广告将不会展示给该玩家。但是屏蔽广告的玩家将不能发布广告，已经发布的广告也不会展示给其他玩家。

广告展示全部消耗或玩家撤回后，从 `ads.yml` 中删除。当 `ads.yml` 中有可用广告时，即向全体在线玩家广播文本，例如 `[Ads by some_player] ads text here`。每一次展示时获取在线玩家的数量并算作本次广告的展示量，如果 `count-afk` 设置为 `false` 则展示量减去 afk 中的玩家。如果剩余展示次数不足当前在线玩家数量则消耗所有剩余的展示次数向最大可能的在线玩家展示，另一部分玩家展示新的广告。

发布广告的权限组是 `heh.ads` 默认 `all`。
