### ISSUE TITLE
新功能：home / back 类传送

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#26]
用于结合 Essential 的 home/back/sethome 提供更合理的开支

### 配置

```
teleport:
  enable: true
  sethome:
    base: 100
    distance: 200
    increment: 10
    world: 50
  home:
    base: 10
    distance: 200
    increment: 5
    world: 20
  back:
    base: 100
    distance: 200
    increment: 20
    world: 20
```

* `enable` 控制是否 override essentials home 的功能
* `sethome` `home` 和 `back` 均直接调用 essentials 的功能实现
* 价格计算：
  * `base` 为起步价
  * `distance` 为加价距离
  * `increment` 为每个加价距离的加价
  * `world` 为切换世界的额外价格
* 计算方式为当前坐标到目的坐标的直线距离。如果切换了世界，计算方式为切换世界价格 + 从目标世界 spawn 位置到目标坐标的直线距离
* home 数量的限制由 essentials 控制
