### ISSUE TITLE
修改signshop数量

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/HamsterEcoHelper#40]
这里的数值不知道应该是什么格式。我把花括号去掉写数字以及在括号内也数字后每次重启都会变回原样
![TIM截图20180303163554.png](https://i.loli.net/2018/03/03/5a9a5eae10642.png)

顺便给乐透功能加个权限吧

**Comment by cyilin** [comment]
格式大概是这样：
```
signshop:
  slot_limit:
    default: 10
    test: 100
```
可以任意增加
对应权限就是`heh.signshop_sign_limit.default`和`heh.signshop_slot_limit.default`，如果玩家有多个权限的话会取最大的那个。
抽奖命令的权限是`heh.signshop.lotto`
