### ISSUE TITLE
v8 重构计划

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#67]
## 功能

- 命令接口
  - [x] 用户命令
  - [ ] 管理员命令
  - [ ] 消息互动命令
- [x] 语言文件
- 全球市场（天喵）
  - [x] 天喵
  - [x] 上架费用
  - [ ] 物品有效期：有效期后自动下架保存在临时存储，每 24h 收取价格 % 的保管费用直到玩家取回
- 木牌商店（玩家/系统）
  - [x] 收购
  - [x] 出售
  - [x] 乐透
- [x] 展示框商店
  - 用作卖出
  - 设置后展示店内随机物品，每个物品只能在一个展示框里展示。如果是堆叠物品，一次交易只购买一个，且原物品不消失（可继续购买）。另购买时需确认该物品是否仍有库存
  - 两次点击确认交易取出物品
  - 只能在合理位置设置展示框
- 拍卖/征购
  - [x] 玩家拍卖/征购
  - [x] 拥有权限的管理员以系统身份拍卖/征购
  - [ ] 系统自动拍卖/征购
- [x] 担保交易（天喵直送，可配置交易等待时间，超时自动取消）
- [x] 系统余额（HEH 内置 / Vault 账户）
- [x] 税务
- [ ] 搜索
  - 搜索所有天喵和木牌商店中的物品，包括材料、名称、lore 和附魔
  - 搜索需要同时展示商店位置信息（天喵、木牌坐标等）
- 管理工具
  - [x] 所有在任意途径出售的物品都有 UID
  - [ ] 删除特定玩家的所有木牌信息
  - [ ] 删除特定玩家的特定物品/所有物品
- [x] API
- [ ] 性能问题（主要是天喵，NBT 相关

广告功能并没有人用所以不要了。

## 配置

`config.yml`

```
language: en_US
balance:
  base: 10000 # system balance base, used in automation.
  vault: SYSTEM # SYSTEM = use HEH system balance, 'player' value is ignored. PLAYER = use player vault account.
  player: 073f34981d8043bb962757e7a4989c1c # player UUID
tax:
  market: 10
  signshop: 5
  direct: 5
  auction: 20
  requisition: 5
fee:
  market:
    base: 100
    storage: 10
  signshop:
    base: 0
  direct:
    base: 50
  auction:
    base: 100
  requisition:
    base: 50
limits:
  slots:
    market: 5
    signshop: 100
  signs: 3
  frames: 12
```

`automation.yml`  - 自动化用配置，暂不开发

## 命令

所有命令默认权限都是 op，需要手动赋予玩家组。

| Command | Permission | Desc |
| --- | --- | --- |
| `/h [m\|market]` | `heh.business.market` | 打开商城 |
| `/h [m\|market] <unit price>` | `heh.business.market` | 上架到天喵 / 购买物品 |
| `/h shop [sell\|buy] [unit price]` | `heh.business.signshop` | 使用木牌商店 |
| `/h chest req` | `heh.business.chest.req` | 指定收购箱子 |
| `/h chest lotto` | `heh.business.chest.lotto` | 指定 lotto 箱子 |
| `/h auc [base] [step] <reserve>` | `heh.business.auction` | 拍卖 |
| `/h req [material\|HAND] [unit price] [amount] <additional params...>` | `heh.business.requisition` | 收购 |
| `/h bid <price>` | `heh.business.bid` | 出价到当前拍卖，如无 `price` 参数则出最低加价 |
| `/h sell <amount>` | `heh.business.sell` | 出售到当前征购 |
| `/h sellto [player] [unit price]` | `heh.business.sellto` | 直接出售给特定玩家 |
| `/h pay [invoice id]` | `heh.business.pay` | 支付账单 |
| `/h cancel [invoice id]` | `heh.business.cancel` | 取消账单 |
| `/h frame` | `heh.business.frame` | 设置物品展示框 |
| `/h storage` | `heh.storage` | 打开临时存储（只能取回） |
| `/h search <params...>` | `heh.search` | 搜索 |
| `/heh balance [view\|pay\|take] <params...>` | `heh.admin.balance` | 管理系统余额 |
| `/heh remove [item\|shop\|player\|storage] [item id\|player name\|sign]` | `heh.admin.remove` | 移除特定物品/玩家数据/木牌或展示框等商店实体 |
| `/heh run auc\|req <params...>` | `heh.admin.run` | 以系统身份执行拍卖/征购 |
